name: GitHub Action to run continuous integration.
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches:
      - main

jobs:
  ci:
    if: ${{ ! contains(github.event.head_commit.message, '#skip-ci') }}
    runs-on: ubuntu-latest    
    steps:
      - run: exit 1
